version: "3"

services:
  app:
    container_name: customer-service
    restart: always
    build: .
    environment: 
      - PORT=4000
    ports: 
      - "4000:4000" 
    command: >
      sh -c "npm run dev"