# version: '3.8'
# services:
#   api:
#     container_name: customer
#     restart: on-failure
#     build: .
#     volumes:
#       - ./src:/app/src
#     ports:
#       - "4000:4000"
#     command: >
#       sh -c "npm start"

version: "3"

services:
  app:
    container_name: customer-app
    restart: always
    build: .
    environment: 
      - PORT=4001 
    ports: 
      - "4001:4001" 
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017" 